#!/bin/bash
#PBS -N l2p-pytorch
#PBS -l select=1:ncpus=8:mem=5G:ngpus=1
#PBS -l walltime=2:00:00
#PBS -P personal
#PBS -j oe
#PBS -o high31415.txt
#PBS -q normal

module load cuda/11.8.0
module load python/3.11.7-gcc11

# (Optional) Activate virtual environment
# source myenv/bin/activate

torchrun --nproc_per_node=1 main.py icmem_l2p --model vit_base_patch16_224_dino \
--output_dir icmem_output --baseline_file high_mem_images.json \
--replay_size 20 --shuffle True --seed 31415
